<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <LangVersion>7.3</LangVersion>
    <CodePage>65001</CodePage>
    <Platforms>x64</Platforms>
    <PlatformTarget>x64</PlatformTarget>
    <AssemblyName>MechKitSetup</AssemblyName>
    <RootNamespace>MechKit.Setup</RootNamespace>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <AppendPlatformToOutputPath>false</AppendPlatformToOutputPath>
    <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
    <Product>MechKit 安装程序</Product>
    <AssemblyTitle>MechKit 安装程序</AssemblyTitle>
    <Version>0.1.0</Version>
  </PropertyGroup>

</Project>
